version: '3.1'

services:
  web:
    image: nginx:1.23
    ports:
      - "8888:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
  app:
    build: .
    volumes:
      - .:/app

  db:
    hostname: db
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=root_password
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
    volumes:
      - pgdata:/var/lib/postgresql/data


  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
